### ISSUE TITLE
Problem with table res.users

### ISSUE THREAD

**Issue by DavidArcos07** [patricoos/PortaCapena.OdooJsonRpcClient#11]
I am trying to consult the information of a user from the res.users table with the administrator credentials but the Odoo Server error returns, it could help me to know what part I am doing wrong.

 private readonly OdooSetting _odooSetting;
        private OdooClient _odooClient;
        private OdooConfig _config;
        public UserOdooService(IOptions<OdooSetting> odooSettingsAccessor)
        {
            _odooSetting = odooSettingsAccessor.Value;
            _config = new OdooConfig(_odooSetting.ApiURL, _odooSetting.Database, _odooSetting.Username, _odooSetting.Password);            
            _odooClient = new OdooClient(_config);
        }

        async Task<ResUsersOdooModel> IUserOdooService.GetUser(long userId)
        {
            OdooRepository<ResUsersOdooModel> repository = new OdooRepository<ResUsersOdooModel>(_config);
            var user = await repository.Query()
                .Where(w => w.Id, OdooOperator.EqualsTo, userId)
                .FirstOrDefaultAsync();

            return user.Value;
        }

**Comment by patricoos** [comment]
Looks good. Can U send also error message?

**Comment by DavidArcos07** [comment]
The error that returns is the following:
Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Employees / Officer
- Employees / Manager
- Administration / Settings
- User types / Internal User

Do you know how I can change these privileges?
