### ISSUE TITLE
OdooConfig language not working

### ISSUE THREAD

**Issue by wesleykappen** [patricoos/PortaCapena.OdooJsonRpcClient#14]
Hi,

First of all, thank you very much for this package and the effort!

I'm running into an issue with the translations, in Odoo we have 2 languages (chinese and English US). When setting the client config like so:

`var config = new OdooConfig(
          apiUrl: _apiEndpoint,
          dbName: _apiDatabase,
          userName: _apiUsername,
          password: _apiPassword,
          language: "en_US",
          timezone: "Europe/Brussels"
        );`

The translation is not working, i'm not getting the correct translations when reading products.

For fullness this is the code i'm using:

`var odooClient = new OdooClient(config);
        var versionResult = odooClient.GetVersionAsync().Result;

        var loginResult = odooClient.LoginAsync().Result;

        var tableName = "product.product";
        var repository = new OdooRepository<ProductProductOdooModel>(config);
        var products = repository.Query()
                .Where(x => x.Barcode, OdooOperator.EqualsTo, "5704854708512")
                .Select(x => new
                {
                  x.Name,
                  x.Description,
                  x.WriteDate
                })
                .OrderByDescending(x => x.Id)
                .Take(10)
                .FirstOrDefaultAsync().Result.Value.Name;`

It's just for testing, but I'm receiving the product as intended, but still with the default chinese language. When I'm using a tool like Fiddler, i'm not seeing the language being sent to the server at all. So I'm either doing something wrong, or the ClientConfig is not respecting the 'Language' field.

Please advise on how to continue or if this is perhaps a bug indeed.

**Comment by patricoos** [comment]
Hello,
I never use this field and multiple languages. I have read some documentation and I think I have a solution for that issue. I can add a new version of my library, but I need some time to test it. It would be faster if I would probably test it on your environment.

**Comment by patricoos** [comment]
In version 1.0.13 will be available selecting language in 2 ways: 

`   
Config.Context.Language = "nl_BE";
var repository = new OdooRepository<ProductProductOdooDto>(Config);
repository.Context.Language = "nl_BE";
`
