### ISSUE TITLE
Filter diferent fields

### ISSUE THREAD

**Issue by lozo2010** [patricoos/PortaCapena.OdooJsonRpcClient#18]
Hi.

I would like to be able to filter by several fields at the same time in a single query.

I have tried different ways, but i have next error;
`
AssertionError: This domain is syntactically not correct: [['name', '=', '15009700'], '|', ['barcode', '=', '15009700']]`

Is this search form correct?

```
OdooFilter filter = new OdooFilter();
filter.EqualTo("name", productid_ean);
filter.Or();
filter.EqualTo("barcode", productid_ean);

var productBarcode = await repository.Query()
              .Where(filter)
              .OrderByDescending(x => x.Id)
              .FirstOrDefaultAsync();
```

**Comment by patricoos** [comment]
U don't need OR. Use multiple times `Where` method
```
repo.Query()
.Where(x => x.Barcode, OdooOperator.EqualsTo, "barcodetest1")
.Where(x => x.Name, OdooOperator.EqualsTo, "name")
.ToListAsync();
```
