### ISSUE TITLE
Unable to connect with Odoo using VB.Net

### ISSUE THREAD

**Issue by manjusha-baranwal-github** [patricoos/PortaCapena.OdooJsonRpcClient#21]
I have tried below code to make connection with Odoo, but i am not getting response from Odoo. is there any settings in Odoo which i need to enable or any mistake in my code, please suggest.
Please help asap.
Imports PortaCapena.OdooJsonRpcClient

 Private Async Function LoginToODOO() As Task
        Try
            Dim objclient As PortaCapena.OdooJsonRpcClient.OdooClient
            Dim config As New Models.OdooConfig("http://127.0.0.1/8069/", "mydb", "mydb@gmail.com", "XXXXX")

            objclient = New OdooClient(config)
            Dim versionResult As Object = Await objclient.GetVersionAsync()
            Dim loginResult As Object = Await objclient.LoginAsync()
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Function

**Comment by manjusha-baranwal-github** [comment]
[ODOO_Connector.zip](https://github.com/patricoos/PortaCapena.OdooJsonRpcClient/files/6669004/ODOO_Connector.zip)
I have attached code here. using  url  ,dbname , username and password i am able to login. but after removing slash on end of url, still not working.

**Comment by patricoos** [comment]
I don't know this language. What's the result of `GetVersionAsync()` method?

**Comment by manjusha-baranwal-github** [comment]
No response coming from  GetVersionAsync() method.

**Comment by patricoos** [comment]
There is something wrong with Your implementation. I create console aplication in VB and it works. Try it
```
Imports System
Imports PortaCapena.OdooJsonRpcClient

Module Program
    Sub Main(args As String())
        Try
            LoginToODOO().GetAwaiter().GetResult()
        Catch ex As Exception
            Console.WriteLine(ex.Message)
        End Try
    End Sub

    Private Async Function LoginToODOO() As Task
        Try
            Dim objclient As PortaCapena.OdooJsonRpcClient.OdooClient
            Dim config As New Models.OdooConfig("http://localhost:8069", "db-test", "admin", "admin")

            objclient = New OdooClient(config)
            Dim versionResult = Await objclient.GetVersionAsync()
            Dim loginResult = Await objclient.LoginAsync()
        Catch ex As Exception
            Console.WriteLine(ex.Message)
        End Try
    End Function

End Module

```

**Comment by patricoos** [comment]
To fix Your code make Button1_Click event handler `Async`. 

```

Imports PortaCapena.OdooJsonRpcClient

Public Class Form1
    Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Try
            Await LoginToODOO()

        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Sub
    Private Async Function LoginToODOO() As Task
        Try
            Dim objclient As PortaCapena.OdooJsonRpcClient.OdooClient
            Dim config As New Models.OdooConfig("http://localhost:8069", "db-test", "admin", "admin")

            objclient = New OdooClient(config)
            Dim versionResult = Await objclient.GetVersionAsync()
            Dim loginResult = Await objclient.LoginAsync()
        Catch ex As Exception
            MessageBox.Show(ex.Message)
        End Try
    End Function

End Class

```

**Comment by manjusha-baranwal-github** [comment]
I am very sorry, but getting below error while executing below lines. Screenshot attached, can you please help. 

Dim versionResult = Await objclient.GetVersionAsync()
            Dim loginResult = Await objclient.LoginAsync()
![OdooError](https://user-images.githubusercontent.com/86042364/122383369-6318be80-cf88-11eb-8e32-5e17882f2ccb.jpg)
![odooerror2](https://user-images.githubusercontent.com/86042364/122383854-cc003680-cf88-11eb-9dfc-e9c1e94cafca.jpg)


Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PortaCapena.OdooJsonRpcClient.OdooClient.CallAndDeserializeAsync[T](OdooRequestModel request)

**Comment by patricoos** [comment]
I send U working example.... Your url is wrong...  http://127.0.0.1/8069 => http://127.0.0.1:8069

**Comment by manjusha-baranwal-github** [comment]
Hi Patric, thank you for quick response, i have tested with consol application and it is working fine at my end also.
my application is built in .Netframework 4.7.2. suggest me how can i use your libraries for Odoo connection and execution of APIs. Once i am using  PortaCapena.Odoo library with my app, no response is coming from Odoo.

How PortaCapena.Odoo library will with Odoo 14 and .Netframework 4.7.2
