### ISSUE TITLE
Error when calling GetModelAsync with Odoo V15 (Master branch)

### ISSUE THREAD

**Issue by chrisandrewmann** [patricoos/PortaCapena.OdooJsonRpcClient#25]
Error = {System.Exception: Not implemented json mapping value: '$"related": "activity_ids.user_id"' to String[]
   at PortaCapena.OdooJsonRpcClient.Converters.OdooModelMapper.ConverOdooPropertyToDotNet(Type dotnetType, JToken value, Object& result)
   
OdooRespository<T> still seems to work fine but getting model mapping must be done with an older version beforehand.

**Comment by patricoos** [comment]
What table did you use?

**Comment by chrisandrewmann** [comment]
Hi @patricoos. Sorry can't be sure but I tried a few including res.partner, crm.lead, sale.order, purchase.order and project.task.
I've actually abandoned the project and moved back to using XML-RPC instead for now, but would be good to know if the problem was with my code.

**Comment by OdooClass** [comment]
Having the same issue using this library with Odoo 15. Something must have changed in the way Odoo is packaging up the related fields.  Definitely would like to see a fix if someone has one.

**Comment by patricoos** [comment]
[Release 1.0.17](https://github.com/patricoos/PortaCapena.OdooJsonRpcClient/releases/tag/1.0.17)
