### ISSUE TITLE
Invalid SSL certificate and basic authentication (htaccess)

### ISSUE THREAD

**Issue by Freddyvdh** [patricoos/PortaCapena.OdooJsonRpcClient#38]
Hi,

thanks a lot for the project!

We want to migrate data from our current CRM to Odoo and just started working with the API. I had problems, because only our Live System has a valid SSL certificate. Our test systems are using 'invalid' self signed certificates and have a basic authentication (htaccess) for protection.

I made some extentions to the code to get this running. Are you interested in these changes? Shall I make a pull request?

Freddy

**Comment by patricoos** [comment]
Hi, I'm glad you are using this library! I will be very grateful for adding this pull request!
