### ISSUE TITLE
Add licence to repository

### ISSUE THREAD

**Issue by Bert-Proesmans** [patricoos/PortaCapena.OdooJsonRpcClient#43]
Hi, in order to use this library in my organisation there needs to be a definition of what is/is not allowed with the code. A licence will help protect your rights as owner, and me/my organisation as consumer.

Are you willing to add a licence to this repository?

**Comment by patricoos** [comment]
Hi, Can you send me any license to follow the example?

**Comment by Bert-Proesmans** [comment]
Hi, the procedure to introduce a licence is a few steps;

1. Pick a licence
2. Get all contributors to agree
3. Write out the chosen licence text in a LICENCE file at the root of the repository (this is a conventional approach)
4. (If necessary) Add licence header to the files in your repository

Picking a licence (1) is something you'll have to do yourself, this is actually a pretty important decision since it defines the freedoms, and limitations, and conditions, others have with your copyrighted material (aka your code).  
For a quick overview check https://choosealicense.com/, but be aware there are many licences and the differences are not always easy to grasp.  
You could follow the licence used by Odoo LGPL (https://choosealicense.com/licenses/gpl-3.0/), see https://github.com/odoo/odoo/blob/fcc74186330c8df37cfac08455bd7bba44d4656b/LICENSE
Or keep it short and straightforward, use MIT (https://choosealicense.com/licenses/mit/)

As for agreement between contributors (2) I explicitly agree to have my contributions be licenced under any licence you pick.
It would help me if that licence allowed "commercial use" and "modification"!

**Comment by MZabal** [comment]
Hi, 
The library looks great! we are also interested in using it in my org.
I just made a pull request adding a MIT license file following @Bert-Proesmans example.
